/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coleccionPersonalDif.Index;

/**
 *
 * @author Manuel
 */
public class InterfazWuay extends javax.swing.JFrame {

    /**
     * Creates new form InterfazWuay
     */
    public InterfazWuay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFechaDeCreacion = new javax.swing.JLabel();
        txtFieldYear = new javax.swing.JTextField();
        txtFieldMes = new javax.swing.JTextField();
        txtFieldDia = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtFieldDescripcion = new javax.swing.JTextField();
        rbtnBaja = new javax.swing.JRadioButton();
        rbtnMedia = new javax.swing.JRadioButton();
        rbtnAlta = new javax.swing.JRadioButton();
        rbtnAhora = new javax.swing.JRadioButton();
        lblFechaDeFinalizacion = new javax.swing.JLabel();
        txtFieldYearFinal = new javax.swing.JTextField();
        txtFieldMesFinal = new javax.swing.JTextField();
        txtFieldDiaFinal = new javax.swing.JTextField();
        lblAdorno = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        lblFechaDeCreacionDone = new javax.swing.JLabel();
        txtFieldYearDone = new javax.swing.JTextField();
        txtFieldMesDone = new javax.swing.JTextField();
        txtFieldDiaDone = new javax.swing.JTextField();
        lblTitleList1 = new javax.swing.JLabel();
        lblTitleList2 = new javax.swing.JLabel();
        lblDescripcionDone = new javax.swing.JLabel();
        txtFieldDescripcionDone = new javax.swing.JTextField();
        rbtnBajaDone = new javax.swing.JRadioButton();
        rbtnMediaDone = new javax.swing.JRadioButton();
        rbtnAltaDone = new javax.swing.JRadioButton();
        rbtnAhoraDone = new javax.swing.JRadioButton();
        btnEnviarDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTitle.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("AGENDA");

        lblFechaDeCreacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaDeCreacion.setText("Fecha de Creacion");

        txtFieldYear.setText("Year");

        txtFieldMes.setText("Mes");

        txtFieldDia.setText("Dia");

        lblDescripcion.setText("Descripcion");

        txtFieldDescripcion.setText("Desc.Tarea");

        rbtnBaja.setText("Baja");

        rbtnMedia.setText("Media");

        rbtnAlta.setSelected(true);
        rbtnAlta.setText("Alta");

        rbtnAhora.setText("Ahora");

        lblFechaDeFinalizacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaDeFinalizacion.setText("Fecha de Finalizacion");

        txtFieldYearFinal.setText("Year");

        txtFieldMesFinal.setText("Mes");

        txtFieldDiaFinal.setText("Dia");

        lblAdorno.setText("--------------------------------------------------------------------------------------------------------------------------------------");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        lblFechaDeCreacionDone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaDeCreacionDone.setText("Fecha de Creacion");

        txtFieldYearDone.setText("Year");

        txtFieldMesDone.setText("Mes");

        txtFieldDiaDone.setText("Dia");

        lblTitleList1.setText("ToDoList");

        lblTitleList2.setText("DoneList");

        lblDescripcionDone.setText("Descripcion");

        txtFieldDescripcionDone.setText("Desc.Tarea");

        rbtnBajaDone.setText("Baja");

        rbtnMediaDone.setText("Media");

        rbtnAltaDone.setSelected(true);
        rbtnAltaDone.setText("Alta");

        rbtnAhoraDone.setText("Ahora");

        btnEnviarDone.setText("Enviar");
        btnEnviarDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarDoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblDescripcion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtFieldDescripcion))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblFechaDeCreacion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(rbtnBaja)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnMedia)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnAlta)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnAhora))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnEnviar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFechaDeFinalizacion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFieldYearFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFieldMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFieldDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAdorno))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblTitleList1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblTitleList2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblDescripcionDone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFieldDescripcionDone))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblFechaDeCreacionDone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFieldYearDone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFieldMesDone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFieldDiaDone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbtnBajaDone)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnEnviarDone))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnMediaDone)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnAltaDone)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnAhoraDone)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitleList1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaDeCreacion)
                    .addComponent(txtFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnBaja)
                    .addComponent(rbtnMedia)
                    .addComponent(rbtnAlta)
                    .addComponent(rbtnAhora))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaDeFinalizacion)
                    .addComponent(txtFieldYearFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(btnEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdorno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitleList2)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaDeCreacionDone)
                    .addComponent(txtFieldYearDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldMesDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldDiaDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcionDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFieldDescripcionDone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnBajaDone)
                    .addComponent(rbtnMediaDone)
                    .addComponent(rbtnAltaDone)
                    .addComponent(rbtnAhoraDone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviarDone)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnEnviarDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarDoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazWuay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazWuay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazWuay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazWuay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazWuay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnEnviarDone;
    private javax.swing.JLabel lblAdorno;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescripcionDone;
    private javax.swing.JLabel lblFechaDeCreacion;
    private javax.swing.JLabel lblFechaDeCreacionDone;
    private javax.swing.JLabel lblFechaDeFinalizacion;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleList1;
    private javax.swing.JLabel lblTitleList2;
    private javax.swing.JRadioButton rbtnAhora;
    private javax.swing.JRadioButton rbtnAhoraDone;
    private javax.swing.JRadioButton rbtnAlta;
    private javax.swing.JRadioButton rbtnAltaDone;
    private javax.swing.JRadioButton rbtnBaja;
    private javax.swing.JRadioButton rbtnBajaDone;
    private javax.swing.JRadioButton rbtnMedia;
    private javax.swing.JRadioButton rbtnMediaDone;
    private javax.swing.JTextField txtFieldDescripcion;
    private javax.swing.JTextField txtFieldDescripcionDone;
    private javax.swing.JTextField txtFieldDia;
    private javax.swing.JTextField txtFieldDiaDone;
    private javax.swing.JTextField txtFieldDiaFinal;
    private javax.swing.JTextField txtFieldMes;
    private javax.swing.JTextField txtFieldMesDone;
    private javax.swing.JTextField txtFieldMesFinal;
    private javax.swing.JTextField txtFieldYear;
    private javax.swing.JTextField txtFieldYearDone;
    private javax.swing.JTextField txtFieldYearFinal;
    // End of variables declaration//GEN-END:variables
}
